name: Build and Release

on:
  push:
    tags: ['v*']  # 标签触发（如 v1.0.0）
  workflow_dispatch:
    inputs:
      version:
        description: '版本号（需带 v 前缀，如 v1.0.0）'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 提取版本号
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      # 关键修复：单行命令，无续行符
      - name: 打包仓库内容
        run: |
          zip -r "release-${{ steps.get_version.outputs.VERSION }}.zip" . -x "*.git*" -x ".github/" -x "release-*.zip"
        shell: bash  # 强制用 bash，避免 sh 的兼容问题

      - name: 创建 Release 并上传
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            **触发方式**：${{ github.event_name == 'workflow_dispatch' && '手动触发' || '标签自动触发' }}  
            **包含文件**：仓库所有文件（排除 .git、.github 和旧打包文件）
          files: release-${{ steps.get_version.outputs.VERSION }}.zip
          draft: false
          prerelease: false
