name: Build and Release

on:
  push:
    tags: ['v*']

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 提取版本号
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: 打包仓库（单行命令，避免续行问题）
        run: |
          zip -r "release-${{ steps.get_version.outputs.VERSION }}.zip" . \
            -x "*.git*" \
            -x ".github/" \
            -x "release-*.zip"
        # 关键：在 YAML 的 `run` 中，用 `|` 或 `\` 续行时，确保 Runner 使用 bash 而非 sh！
        shell: bash  # 强制使用 bash 执行，避免 sh 的兼容性问题

      - name: 创建 Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: "自动打包，包含仓库所有文件（排除 .git、.github 和旧打包文件）"
          draft: false
          prerelease: false

      - name: 上传资产
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: release-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
